### ISSUE TITLE
No module named nxsvg

### ISSUE THREAD

**Issue by a-t-0** [rainwoodman/nxsvg#1]
Thank you for your work, I was wondering whether exporting as svg may be faster than exporting to png.

When I try to run your code locally:

```py
$python example.py
Traceback (most recent call last):
  File "example.py", line 5, in <module>
    import nxsvg
ModuleNotFoundError: No module named 'nxsvg'

```
I'lll get the error:
```
$python example.py
Traceback (most recent call last):
  File "example.py", line 5, in <module>
    import nxsvg
ModuleNotFoundError: No module named 'nxsvg'
```
So I tried `pip install nxsvg` however, that package does not exist. Would you happen to be able to specify how I can use your code?

**Comment by a-t-0** [comment]
Sorry, I did not realise I had to put the `example.py` inside the `src/` directory, such that the `import nxsvg` is actually a file instead of pip package that one imports.

**Comment by rainwoodman** [comment]
Glad you figured it out. Yes this was not packaged as a pip package.
